FROM gcr.io/google.com/cloudsdktool/cloud-sdk:latest
#
## install gsutil lightly
#RUN  apt update \
#  && apt install -y wget
#RUN wget https://storage.googleapis.com/pub/gsutil.tar.gz
#RUN tar xfz gsutil.tar.gz -C $HOME
#ENV PATH="${PATH}:$HOME/gsutil"

COPY ./run.sh /run.sh
